# Generated by Django 4.0.4 on 2022-04-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
                ('comments', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Роли пользователей',
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя пользователя')),
                ('email', models.CharField(max_length=100, verbose_name='e-mail')),
                ('phone_num', models.CharField(max_length=100, verbose_name='Телефоны')),
                ('comments', models.CharField(max_length=100, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'db_table': 'Users',
            },
        ),
    ]
