# Generated by Django 4.0.4 on 2022-04-18 12:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Населенные пункты',
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='EduOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наименование')),
                ('short_name', models.CharField(max_length=20, unique=True, verbose_name='Короткое наименование')),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainapp.city')),
            ],
            options={
                'verbose_name': 'Учебные заведения',
                'db_table': 'EduOrg',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='birth_date',
            field=models.DateField(default=datetime.date(2022, 4, 18), verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='users',
            name='gender',
            field=models.IntegerField(choices=[('Мужской', 1), ('Женский', 2)], default=1, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='users',
            name='home_address',
            field=models.CharField(blank=True, max_length=150, verbose_name='Домашний адрес'),
        ),
        migrations.CreateModel(
            name='UserEdu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('edu_type', models.IntegerField(choices=[('Высшее образование', 1), ('Среднее специальное образование', 2), ('Повышение квалификации / Переквалификация', 3)], default=1, verbose_name='Уровень образования')),
                ('comments', models.CharField(max_length=100, verbose_name='Примечание')),
                ('edu_org_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainapp.eduorg')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainapp.users')),
            ],
            options={
                'verbose_name': 'ОБразование',
                'db_table': 'UserEdu',
            },
        ),
    ]
