# Generated by Django 4.0.4 on 2022-04-26 01:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_companyprofile_alter_useredu_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='is_edu',
            field=models.BooleanField(null=True, verbose_name='Образовательное учреждение'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='mainapp.users'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(default=datetime.date(2022, 4, 26), verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='mainapp.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='comments',
            field=models.CharField(blank=True, max_length=100, verbose_name='Примечание'),
        ),
    ]
