# Generated by Django 4.0.4 on 2022-04-26 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_companyprofile_is_edu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='city_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='mainapp.city'),
        ),
    ]
