# Generated by Django 4.0.4 on 2022-04-26 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_companyprofile_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='mainapp.city'),
        ),
    ]
