# Generated by Django 4.0.4 on 2022-04-26 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_userprofile_city_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50, verbose_name='Должность')),
                ('work_experience', models.CharField(blank=True, max_length=50, verbose_name='Опыт работы')),
                ('work_mode', models.IntegerField(choices=[('Полный рабочий день', 1), ('Частичная занятость', 2), ('Удаленное место работы', 3), ('Вахтовый метод работы', 3), ('Проектная работа', 3)], default=1, verbose_name='Тип занятости')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования к кандидату')),
                ('conditions', models.TextField(blank=True, verbose_name='Условия работы')),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainapp.city')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainapp.users')),
            ],
            options={
                'verbose_name': 'Вакансии',
                'db_table': 'Vacancy',
            },
        ),
    ]
