# Generated by Django 4.0.4 on 2022-04-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_vacancy_min_salary_vacancy_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='short_name',
            field=models.CharField(max_length=20, verbose_name='Короткое наименование'),
        ),
    ]
