# Generated by Django 4.0.4 on 2022-04-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_companyprofile_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Мужской'), (2, 'Женский')], default=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='work_mode',
            field=models.IntegerField(choices=[(1, 'Полный рабочий день'), (2, 'Частичная занятость'), (3, 'Удаленное место работы'), (4, 'Вахтовый метод работы'), (5, 'Проектная работа')], default=1, verbose_name='Тип занятости'),
        ),
    ]
