# Generated by Django 4.0.4 on 2022-05-02 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_userprofile_gender_alter_vacancy_work_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Категории вакансий',
                'db_table': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='mainapp.categories'),
        ),
    ]
