# Generated by Django 4.0.4 on 2022-05-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_categories_options_alter_vacancy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Статьи', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='articles',
            name='url',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ссылка на статью'),
        ),
    ]
