# Generated by Django 4.0.4 on 2022-05-18 05:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useredu',
            name='edu_org_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Учебное заведение'),
        ),
        migrations.AlterField(
            model_name='users',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 20, 5, 11, 48, 453558, tzinfo=utc)),
        ),
    ]
