# Generated by Django 4.0.4 on 2022-05-21 11:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_useredu_edu_org_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useredu',
            name='edu_type',
            field=models.IntegerField(choices=[(1, 'Высшее образование'), (2, 'Среднее специальное образование'), (3, 'Повышение квалификации / Переквалификация')], default=1, verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='userjobhistory',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='users',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 11, 52, 27, 844395, tzinfo=utc)),
        ),
    ]
