# Generated by Django 4.0.4 on 2022-05-24 01:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_alter_users_activation_key_expires_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Мужской'), (2, 'Женский')], default=1, validators=[mainapp.models.check_gender], verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='users',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 1, 20, 17, 215394, tzinfo=utc)),
        ),
    ]
