# Generated by Django 4.0.4 on 2022-05-25 02:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_alter_useredu_comments_alter_userprofile_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useredu',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='useredu',
            name='edu_org_name',
            field=models.CharField(default='', max_length=100, verbose_name='Учебное заведение'),
        ),
        migrations.AlterField(
            model_name='userjobhistory',
            name='end_date',
            field=models.DateField(blank=True, validators=[mainapp.models.check_end_date], verbose_name='Дата окончания работы'),
        ),
        migrations.AlterField(
            model_name='users',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 2, 12, 12, 273893, tzinfo=utc)),
        ),
    ]
