# Generated by Django 4.0.4 on 2022-05-25 02:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_alter_useredu_comments_alter_useredu_edu_org_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjobhistory',
            name='end_date',
            field=models.DateField(null=True, validators=[mainapp.models.check_end_date], verbose_name='Дата окончания работы'),
        ),
        migrations.AlterField(
            model_name='users',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 2, 21, 48, 418103, tzinfo=utc)),
        ),
    ]
