# Generated by Django 4.0.4 on 2022-05-25 02:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_alter_userjobhistory_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjobhistory',
            name='end_date',
            field=models.DateField(blank=True, null=True, validators=[mainapp.models.check_end_date], verbose_name='Дата окончания работы'),
        ),
        migrations.AlterField(
            model_name='users',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 2, 27, 42, 448372, tzinfo=utc)),
        ),
    ]
