# Generated by Django 4.0.4 on 2022-05-25 02:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_alter_userjobhistory_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 2, 48, 21, 571129, tzinfo=utc)),
        ),
    ]
