# Generated by Django 4.0.4 on 2022-05-25 06:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_alter_useredu_edu_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumes',
            name='publish_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='users',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 6, 8, 9, 838220, tzinfo=utc)),
        ),
    ]
