# Generated by Django 4.0.4 on 2022-05-27 10:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_alter_resumes_publish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useredu',
            name='course_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Факультет/Курс (для переквалификации)'),
        ),
        migrations.AddField(
            model_name='useredu',
            name='skills',
            field=models.CharField(blank=True, max_length=100, verbose_name='Полученная профессия/специальность'),
        ),
        migrations.AlterField(
            model_name='resumes',
            name='min_salary',
            field=models.IntegerField(null=True, verbose_name='Желаемая ЗП'),
        ),
        migrations.AlterField(
            model_name='users',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 10, 30, 50, 740315, tzinfo=utc)),
        ),
    ]
