# Generated by Django 4.0.4 on 2022-05-27 11:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_useredu_course_name_useredu_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjobhistory',
            name='progress',
            field=models.TextField(blank=True, verbose_name='Результат / достижения'),
        ),
        migrations.AlterField(
            model_name='users',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 11, 8, 1, 650365, tzinfo=utc)),
        ),
    ]
