# Generated by Django 4.0.4 on 2022-05-27 11:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_alter_userjobhistory_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Дополнительные сведения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hard_skills',
            field=models.TextField(blank=True, verbose_name='hard skills'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='soft_skills',
            field=models.TextField(blank=True, verbose_name='soft skills'),
        ),
        migrations.AlterField(
            model_name='users',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 11, 9, 21, 891123, tzinfo=utc)),
        ),
    ]
