# Generated by Django 4.0.4 on 2022-05-31 01:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_alter_users_activation_key_expires'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name': 'Профиль компании'},
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='activity_field',
            field=models.TextField(max_length=400, null=True, verbose_name='Сфера деятельности'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(max_length=400, null=True, verbose_name='Приветственное письмо'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='other_info',
            field=models.TextField(blank=True, max_length=400, verbose_name='Другая информация'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='site',
            field=models.URLField(blank=True, verbose_name='Сайт'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='education_type',
            field=models.IntegerField(choices=[(1, 'Высшее образование'), (2, 'Среднее специальное образование'), (3, 'Повышение квалификации / Переквалификация')], default=1, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_business_trip',
            field=models.BooleanField(default=False, verbose_name='Готовность к командировкам'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовать'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='relevance',
            field=models.IntegerField(choices=[(1, 'active'), (2, 'closed')], default=1, verbose_name='Актуальность вакансии'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='schedule',
            field=models.IntegerField(choices=[(1, 'Полный день'), (2, 'Гибкий график'), (3, 'Удаленная работа'), (4, 'Сменный график'), (5, 'Вахтовый метод')], default=1, verbose_name='График работы'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='type_of_employment',
            field=models.IntegerField(choices=[(1, 'Полная занятость'), (2, 'Частичная занятость'), (3, 'Проектная работа'), (4, 'Стажировка'), (5, 'Волонтерство')], default=1, verbose_name='Тип занятости'),
        ),
        migrations.AlterField(
            model_name='users',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 1, 17, 12, 854620, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('content', models.TextField(max_length=1000, verbose_name='Отзыв')),
                ('publication_date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='mainapp.users', verbose_name='От кого')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='mainapp.users', verbose_name='Кому')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'Review',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('photo', models.ImageField(blank=True, upload_to='photo_news', verbose_name='Фото')),
                ('content', models.TextField(max_length=1000, verbose_name='Содержание')),
                ('publication_date', models.DateField(auto_now=True, verbose_name='Дата публикации')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainapp.users')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
                'db_table': 'News',
            },
        ),
    ]
