# Generated by Django 4.0.4 on 2022-06-01 05:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_alter_users_activation_key_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='position',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='city_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='mainapp.city', verbose_name='Город места нахождения'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(blank=True, upload_to='avatars', verbose_name='Логотип компании'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo_news', verbose_name='Сопровождающее изображение'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_from', to='mainapp.users', verbose_name='Чей отзыв'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_to', to='mainapp.users', verbose_name='О ком отзыв'),
        ),
        migrations.AlterField(
            model_name='users',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 5, 50, 47, 339314, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='mainapp.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='city_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainapp.city', verbose_name='Город места нахождения вакансии'),
        ),
    ]
