# Generated by Django 4.0.4 on 2022-06-06 13:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_remove_review_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rate',
            field=models.IntegerField(default=1, validators=[mainapp.models.check_rate], verbose_name='Оценка компании'),
        ),
        migrations.AlterField(
            model_name='users',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 13, 30, 20, 994785, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Сообщение')),
                ('send_date', models.DateTimeField(auto_now=True, verbose_name='Дата отправления')),
                ('from_user_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sender', to='mainapp.users', verbose_name='Сообщение от')),
                ('to_user_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='receiver', to='mainapp.users', verbose_name='Сообщение для')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'db_table': 'Message',
            },
        ),
    ]
