# Generated by Django 4.0.4 on 2022-06-09 00:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_review_rate_alter_users_activation_key_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 11, 0, 34, 5, 268785, tzinfo=utc)),
        ),
    ]
