# Generated by Django 4.0.4 on 2022-06-09 03:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_alter_users_activation_key_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='useredu',
            name='photo',
            field=models.ImageField(blank=True, upload_to='docs', verbose_name='Фото документа об образовании'),
        ),
        migrations.AlterField(
            model_name='users',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 11, 3, 4, 28, 342218, tzinfo=utc)),
        ),
    ]
