# Generated by Django 4.0.4 on 2022-06-09 06:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_useredu_photo_alter_users_activation_key_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply_to_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='mainapp.message'),
        ),
        migrations.AlterField(
            model_name='users',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 11, 6, 39, 7, 76038, tzinfo=utc)),
        ),
    ]
